require:
  - rubocop-rspec
  - './lib/custom_cops/spec_suffix'
  - './lib/custom_cops/consistent_file_path'

AllCops:
  DisabledByDefault: true

CustomCops/SpecSuffix:
  Enabled: true

CustomCops/ConsistentFilePath:
  Enabled: true
